language: go
go:
  - 1.12
  - 1.13
  - 1.14
  - stable
  - tip

env:
  - GO111MODULE=on

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

  - |
    # Ensure the local repository is up-to-date
    build/generate_all.sh
    [ -z "$(git status --porcelain --untracked-files=no)" ] || { >&2 echo "Found untracked changes. Run build/generate_all.sh"; exit 1 }

  - cd cmd/genset && go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
