language: go
go:
  - 1.14
  - stable
  - tip

before_install:
  - GO111MODULE=off go get golang.org/x/tools/cmd/cover
  - GO111MODULE=off go get github.com/mattn/goveralls

script:
  # Ensure the local repository is up-to-date
  - hack/verify_all.sh

  - hack/build_verify_genset.sh

  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
