#!/usr/bin/env bash
set -euo pipefail

DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTNAME="$(basename "${BASH_SOURCE[0]}")"

pushd "$DIR/.." >/dev/null
function reset() {
	popd >/dev/null
}
trap reset EXIT

cp "genericset/zz_genset_test.go" zz_compat_test.go

HEADER="// File generated by $SCRIPTNAME. DO NOT EDIT."$'\\\n'
HEADER+="//go:generate $(realpath --relative-to=. "${BASH_SOURCE[0]}")"$'\\\n'
HEADER+="//"$'\\\n'
HEADER+="// Tests for backwards compatibility of the API surface with genericset."$'\\\n'
HEADER+=$'\\\n'

sed -i '' "s~// File generated by genset. DO NOT EDIT.~$HEADER~" zz_compat_test.go
sed -i '' "s~package genericset~package set~" zz_compat_test.go
perl -pi -e 's/(?<!Test)(New|Intersect|Union|Subtract)Set/\1/' zz_compat_test.go

go fmt .
